/** Venue photography — Tea Coffee Break (GenSan). */

export const images = {
  heroAmbient: "/venue/patio-02.png",
  storyGarden: "/venue/patio-01.png",
  /** Featured card — signature drink photo */
  menuFeatured: "/menu/tcb-drink.png",
  vibe: [
    {
      src: "/venue/patio-01.png",
      alt: "Outdoor seating with grid fence and greenery",
    },
    {
      src: "/venue/patio-02.png",
      alt: "Industrial-rustic patio with plants",
    },
    {
      src: "/venue/patio-03.png",
      alt: "Wooden bench and lush tropical plants",
    },
    {
      src: "/venue/patio-04.png",
      alt: "Slatted wood wall and cozy seating",
    },
    {
      src: "/venue/storefront.png",
      alt: "TCB storefront",
    },
  ] as const,
} as const;

export const venueGallery = [
  {
    src: "/venue/storefront.png",
    alt: "Tea Coffee Break storefront with orange facade",
    caption: "Our door on J. Católico — you can’t miss the orange.",
    wide: true,
  },
  {
    src: "/venue/patio-01.png",
    alt: "Café patio with vines and bar seating",
    caption: "Garden grids & greenery",
  },
  {
    src: "/venue/patio-02.png",
    alt: "Rustic patio tables and corrugated wall",
    caption: "Industrial-rustic corners",
  },
  {
    src: "/venue/patio-03.png",
    alt: "Wood bench and elephant ear plants",
    caption: "Warm wood & jungle calm",
  },
  {
    src: "/venue/patio-04.png",
    alt: "Vertical wood wall with logo circle",
    caption: "Where the wall meets the leaves",
  },
] as const;

export type MenuCategory = "all" | "coffee" | "tea" | "food";

/** Shown under the menu heading — matches in-app voucher messaging */
export const menuPromo =
  "Foodpanda: use voucher code EATNA for ₱100 off when you order above ₱399.";

/** Product photography for the gallery — files in /public/menu */
export const menuGalleryPhotos = [
  { src: "/menu/tcb-drink.png", alt: "TCB signature iced drink" },
  { src: "/menu/iced-caramel-macchiato.png", alt: "Iced Caramel Macchiato" },
  { src: "/menu/iced-dolce-latte.png", alt: "Iced Dolce Latte" },
  { src: "/menu/iced-cappuccino.png", alt: "Iced Cappuccino" },
  { src: "/menu/iced-cafe-latte.png", alt: "Iced Cafe Latte" },
  { src: "/menu/hot-cappuccino-dose.png", alt: "Hot Cappuccino — dose" },
  { src: "/menu/hot-americano-dose.png", alt: "Hot Americano — dose" },
  { src: "/menu/hot-cafe-latte-dose.png", alt: "Hot Cafe Latte — dose" },
  { src: "/menu/hot-caramel-macchiato-dose.png", alt: "Hot Caramel Macchiato — dose" },
  { src: "/menu/iced-passionberry-tea.png", alt: "Iced Passionberry Tea — De Sais" },
  { src: "/menu/beef-tapa.png", alt: "Beef Tapa with rice and egg" },
  { src: "/menu/corned-beef.png", alt: "Corned Beef meal" },
  { src: "/menu/tuna-sandwich.png", alt: "Tuna sandwich" },
  { src: "/menu/chicken-sandwich.png", alt: "Chicken sandwich" },
  { src: "/menu/carbonara.png", alt: "Carbonara pasta" },
] as const;

export const menuItems = [
  {
    id: "tcb-drink",
    category: "coffee" as const,
    featured: true,
    emoji: "🧡",
    name: "TCB Drink",
    desc: "Our signature drink — iced.",
    price: "₱273",
    unit: "/ order",
    photo: "/menu/tcb-drink.png",
  },
  {
    id: "iced-caramel-macchiato",
    category: "coffee" as const,
    featured: false,
    emoji: "🧊",
    name: "Iced Caramel Macchiato",
    desc: "Iced espresso with caramel syrup and whole milk, topped with foam.",
    price: "from ₱220",
    unit: "/ order",
    photo: "/menu/iced-caramel-macchiato.png",
  },
  {
    id: "iced-dolce-latte",
    category: "coffee" as const,
    featured: false,
    emoji: "🧊",
    name: "Iced Dolce Latte",
    desc: "De Sais — two shots of espresso.",
    price: "from ₱220",
    unit: "/ order",
    photo: "/menu/iced-dolce-latte.png",
  },
  {
    id: "iced-cappuccino",
    category: "coffee" as const,
    featured: false,
    emoji: "🧊",
    name: "Iced Cappuccino",
    desc: "Espresso, milk, foam, cinnamon on top (no sugar). De Sais — two shots of espresso.",
    price: "from ₱180",
    unit: "/ order",
    photo: "/menu/iced-cappuccino.png",
  },
  {
    id: "iced-cafe-latte",
    category: "coffee" as const,
    featured: false,
    emoji: "🧊",
    name: "Iced Cafe Latte",
    desc: "Two espresso shots and milk, no sugar — De Sais.",
    price: "from ₱180",
    unit: "/ order",
    photo: "/menu/iced-cafe-latte.png",
  },
  {
    id: "hot-cappuccino-dose",
    category: "coffee" as const,
    featured: false,
    emoji: "☕",
    name: "Hot Cappuccino — Dose",
    desc: "Hot — one shot of espresso.",
    price: "from ₱180",
    unit: "/ hot dose",
    photo: "/menu/hot-cappuccino-dose.png",
  },
  {
    id: "hot-americano-dose",
    category: "coffee" as const,
    featured: false,
    emoji: "☕",
    name: "Hot Americano — Dose",
    desc: "Hot — one shot of espresso.",
    price: "₱160",
    unit: "/ hot dose",
    photo: "/menu/hot-americano-dose.png",
  },
  {
    id: "hot-cafe-latte-dose",
    category: "coffee" as const,
    featured: false,
    emoji: "☕",
    name: "Hot Cafe Latte — Dose",
    desc: "Hot — single espresso.",
    price: "from ₱180",
    unit: "/ hot dose",
    photo: "/menu/hot-cafe-latte-dose.png",
  },
  {
    id: "hot-caramel-macchiato-dose",
    category: "coffee" as const,
    featured: false,
    emoji: "☕",
    name: "Hot Caramel Macchiato — Dose",
    desc: "Hot — one shot of espresso.",
    price: "from ₱190",
    unit: "/ hot dose",
    photo: "/menu/hot-caramel-macchiato-dose.png",
  },
  {
    id: "hot-dolce-latte-dose",
    category: "coffee" as const,
    featured: false,
    emoji: "☕",
    name: "Hot Dolce Latte — Dose",
    desc: "Dolce sauce sweetened with one shot of espresso.",
    price: "from ₱190",
    unit: "/ hot dose",
  },
  {
    id: "hot-white-chocolate-mocha-dose",
    category: "coffee" as const,
    featured: false,
    emoji: "☕",
    name: "Hot White Chocolate Mocha — Dose",
    desc: "White mocha sauce — one shot of espresso.",
    price: "from ₱190",
    unit: "/ hot dose",
  },
  {
    id: "iced-white-chocolate-mocha",
    category: "coffee" as const,
    featured: false,
    emoji: "🧊",
    name: "Iced White Chocolate Mocha",
    desc: "Rich white chocolate and bold espresso over ice.",
    price: "from ₱250",
    unit: "/ order",
  },
  {
    id: "iced-americano",
    category: "coffee" as const,
    featured: false,
    emoji: "🧊",
    name: "Iced Americano",
    desc: "Espresso shot. De Sais is two shots; Bente Dos is three shots.",
    price: "from ₱190",
    unit: "/ order",
  },
  {
    id: "surprise-me-drink",
    category: "coffee" as const,
    featured: false,
    emoji: "✨",
    name: "Surprise Me Drink — De Sais",
    desc: "ICED only — ‘Wala ka kabalo sa orderon na kape, kami na bahala sa imo.’",
    price: "₱285",
    unit: "/ order",
  },
  {
    id: "iced-passionberry-tea",
    category: "tea" as const,
    featured: false,
    emoji: "🍓",
    name: "Iced Passionberry Tea — De Sais",
    desc: "Passionfruit and strawberry tea.",
    price: "₱210",
    unit: "/ order",
    photo: "/menu/iced-passionberry-tea.png",
  },
  {
    id: "hot-passionberry-tea",
    category: "tea" as const,
    featured: false,
    emoji: "🍵",
    name: "Hot Passionberry Tea",
    desc: "Dose size.",
    price: "₱180",
    unit: "/ order",
  },
  {
    id: "willy-wonka",
    category: "tea" as const,
    featured: false,
    emoji: "🍫",
    name: "Willy Wonka",
    desc: "Iced sikwate with hazelnut — non-coffee.",
    price: "₱210",
    unit: "/ order",
  },
  {
    id: "beef-tapa",
    category: "food" as const,
    featured: false,
    emoji: "🍚",
    name: "Beef Tapa",
    desc: "With rice and egg.",
    price: "₱220",
    unit: "/ meal",
    photo: "/menu/beef-tapa.png",
  },
  {
    id: "corned-beef",
    category: "food" as const,
    featured: false,
    emoji: "🍚",
    name: "Corned Beef",
    desc: "With rice and egg — imported corned beef.",
    price: "₱220",
    unit: "/ meal",
    photo: "/menu/corned-beef.png",
  },
  {
    id: "pork-chop",
    category: "food" as const,
    featured: false,
    emoji: "🍚",
    name: "Pork Chop",
    desc: "With rice, egg, and cucumber.",
    price: "₱220",
    unit: "/ meal",
  },
  {
    id: "luncheon-meat",
    category: "food" as const,
    featured: false,
    emoji: "🍚",
    name: "Luncheon Meat",
    desc: "Pork — with rice, egg, and cucumber.",
    price: "₱220",
    unit: "/ meal",
  },
  {
    id: "honey-garlic-chicken",
    category: "food" as const,
    featured: false,
    emoji: "🍗",
    name: "Honey Garlic Chicken",
    desc: "Six pieces chicken wings.",
    price: "₱340",
    unit: "/ order",
  },
  {
    id: "sriracha-chicken-wings",
    category: "food" as const,
    featured: false,
    emoji: "🌶️",
    name: "Sriracha Chicken Wings",
    desc: "Six pieces chicken wings.",
    price: "₱340",
    unit: "/ order",
  },
  {
    id: "tuna-sandwich",
    category: "food" as const,
    featured: false,
    emoji: "🥪",
    name: "Tuna Sandwich",
    desc: "Lettuce, cheddar, tomato, cucumber, tuna flakes, mayo.",
    price: "₱165",
    unit: "/ order",
    photo: "/menu/tuna-sandwich.png",
  },
  {
    id: "chicken-sandwich",
    category: "food" as const,
    featured: false,
    emoji: "🥪",
    name: "Chicken Sandwich",
    desc: "Lettuce, tomato, cucumber.",
    price: "₱165",
    unit: "/ order",
    photo: "/menu/chicken-sandwich.png",
  },
  {
    id: "carbonara",
    category: "food" as const,
    featured: false,
    emoji: "🍝",
    name: "Carbonara",
    desc: "Chicken, parmesan, bell pepper, pasta, creamy white sauce.",
    price: "₱210",
    unit: "/ order",
    photo: "/menu/carbonara.png",
  },
  {
    id: "sss-pasta",
    category: "food" as const,
    featured: false,
    emoji: "🍝",
    name: "SSS Pasta",
    desc: "Spicy Spanish sardines — served with bread.",
    price: "₱210",
    unit: "/ order",
  },
  {
    id: "shrimp-marinara-pasta",
    category: "food" as const,
    featured: false,
    emoji: "🍝",
    name: "Shrimp Marinara Pasta",
    desc: "Medjo aslom ni ha, ayaw katingala.",
    price: "₱210",
    unit: "/ order",
  },
] as const;

export const vibeCards = [
  {
    tag: "Ambiance",
    title: "Hidden Garden Oasis",
    desc: "Step through the gate and discover a lush outdoor sanctuary — greenery, fairy lights, and the open GenSan sky as your ceiling.",
    icon: "🌿",
  },
  {
    tag: "Night Vibes",
    title: "Under the Nightsky",
    desc: "Open until 2AM — because some of the best conversations happen late. Warm lighting, cool breeze, great coffee.",
    icon: "🌙",
  },
  {
    tag: "Craft Coffee",
    title: "Baristas Who Care",
    desc: "Our team obsesses over brew ratios, grind sizes, and temperature — so every cup reaches you at its absolute best.",
    icon: "☕",
  },
  {
    tag: "Community",
    title: "Everyone Belongs Here",
    desc: "Students, couples, remote workers, night owls — TCB is a space where all are welcomed with a genuine smile.",
    icon: "🤝",
  },
  {
    tag: "Eco-Conscious",
    title: "Brewing a Better World",
    desc: "We replaced plastic with recycled milk cartons because we believe good coffee and good values go hand in hand.",
    icon: "♻️",
  },
] as const;

export const reviews = [
  {
    id: "ramzel-delloro",
    text: "wait, pero can we talk about TCB??? Literally saved me during my five-major barrage sa second year.",
    author: "Ramzel Delloro",
  },
  {
    id: "jori-mae-samillano",
    text: "Decided to have a coffee date with myself so I went to my favorite tambayan, Tea Coffee Break. I come here often whenever I want to grab a cup of coffee or just wanted to chill before heading home. So, I just want to thank these kind and sweet staff for always making me feel at home with their warmth and hospitality. Thank you, guys! I was planning to gatekeep this simple but cozy coffee shop but they're too good not to share with others. So go visit them if you like! They're located just across Gmall, beside Novo.",
    author: "Jori Mae Samillano",
  },
  {
    id: "welcoming-baristas",
    text: "YES!! PINAKA WELCOMING NA MGA BARISTAS EVER!!!",
    author: "Facebook comment",
  },
  {
    id: "community-kwentong-tcb",
    text: "Hmmm. Where do I begin 🤣 I can still vividly remember when TCB is starting palang jud. That time, guot kaayo ang place, still working on things, ga delegate palang sila sa ilang mga barista og certain work. Wala siguro'y week that time na dili ko maka visit sa ilang shop, to the point, na sabay nalang mi manguli sa mga barista kay mag close na og kaila nako sa ilang mga barista, shawrawrt sa inyo 😭 warahel. 😩 Funny it may sound, naka gain ko'g friends outside work, like maingon nako close friends, like JC (if ya know what I mean? 🫣🙏). Grabe ka friendly sa mga tao dinhi og dabest ang tambayan sa likord?? san ka pa! I've seen the hardwork jud ni TCB for the past 4years, na witness jud nako firsthand ang growth sa tanan. Og maski kinsa mangutana sa akoa unsa ma recommend na coffee shop diri sa dakbayan. Dakbayan?!!? Dili jud ni mawala, dili man pod bias na kaila nako si Master Jai or ppl behind TCB. Walay atik pero maskin asa nako nalabay na coffeeshop, davest paren talaga ang white chocolate mocha na iced. 😭 Ikaw, anong kwentong TCB mo? Comment down below. Hueyy! 💃🗣️☕️🫂",
    author: "Guest, Facebook",
  },
  {
    id: "starbucks-partner-gensan",
    text: "Coffee in General Santos has been so competitive lately, and now it's all about who can truly sustain their dominance. As a partner at Starbucks Drive-Thru, opening and running this giant for almost a year here in Gensan. I can say there will always be bigger challenges ahead. Seeing the local entrepreneurs build some of the most innovative coffee shops across Gensan (a city of over 600,000+ people) amazes me with how much variety and creativity they bring. Some people ask if I'd put up my own shop. Tbh, at this point in my career, I'm still learning. Others might say I'm scared, but I just brush it off with a smile and a wink chz maybe it's not my path yet, but I'm open to the possibilities. For now, what matters is allowing myself to keep growing and learning. I get caught up with these thoughts especially when I'm in an explorative mood, because I'm obsessed with how much customer service has leveled up in our market. Shoutout to Tea Coffee BreakJai Ra for recovering my concern. Sa totoo lang, it feels refreshing since I'm usually the one and the team doing recoveries all the time! lolz 😝 Most of all, I'd like to appreciate our Starbucks goers/regulars for being so considerate. For me, it's about building a solid foundation of community, delivering the best and right service the Generals truly deserve.",
    author: "Starbucks Drive-Thru partner, GenSan",
  },
] as const;
